# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='favorite_episode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='saved_clips1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='saved_clips2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='saved_clips3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
