# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20170720_2315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcasts',
            new_name='Podcast',
        ),
    ]
