# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20170720_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
