# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20170727_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='shownotes',
            field=models.URLField(blank=True, null=True),
        ),
    ]
