# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_podcast_shownotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
