# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20170801_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.CharField(blank=True, default='Add something', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='favorite_episode',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='logo',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='saved_clips1',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='saved_clips2',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='saved_clips3',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='shownotes',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(blank=True, default='Add something'),
            preserve_default=False,
        ),
    ]
