# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20170801_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(),
        ),
    ]
