# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_podcast_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='saved_clips1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='saved_clips2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='saved_clips3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='shownotes',
            field=models.URLField(blank=True, null=True),
        ),
    ]
