# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_auto_20170817_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
