# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20170817_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='saved_clips1',
            new_name='saved_clip',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='saved_clips2',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='saved_clips3',
        ),
    ]
