# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='logo',
            field=models.URLField(default='http://via.placeholder.com/170x170'),
            preserve_default=False,
        ),
    ]
