# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0020_auto_20170902_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='current_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
