# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0021_friend_current_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='current_users',
            new_name='current_user',
        ),
    ]
